#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"
CONFIG_FILE="$CONFIG_DIR/wallet.conf"
mkdir -p "$CONFIG_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

DEFAULT_BASE_URL="https://rest.budgetbakers.com/wallet/v1/api"
RECONFIGURING=false

if [ -f "$CONFIG_FILE" ]; then
    echo -e "${GREEN}✓${NC} Configuration found: config/wallet.conf"
    read -r -p "Do you want to reconfigure? (y/N): " RECONFIGURE
    if [ "$RECONFIGURE" != "y" ] && [ "$RECONFIGURE" != "Y" ]; then
        echo -e "${GREEN}Setup complete!${NC}"
        exit 0
    fi
    RECONFIGURING=true
    # shellcheck source=/dev/null
    . "$CONFIG_FILE"
else
    echo -e "${YELLOW}!${NC} No configuration found"
fi

read_config_value() {
    local var_name="$1"
    local prompt_text="$2"
    local current_value="$3"
    local default_value="$4"
    local is_required="$5"
    local full_prompt

    if [ "$RECONFIGURING" = true ]; then
        if [ -n "$current_value" ]; then
            full_prompt="$prompt_text [current: $current_value]: "
        else
            full_prompt="$prompt_text [current: not set]: "
        fi
    else
        if [ -n "$default_value" ]; then
            full_prompt="$prompt_text [default: $default_value]: "
        else
            full_prompt="$prompt_text: "
        fi
    fi

    while true; do
        read -r -p "$full_prompt" input_value

        if [ "$RECONFIGURING" = true ] && [ -z "$input_value" ]; then
            input_value="$current_value"
        fi

        if [ -z "$input_value" ] && [ -n "$default_value" ]; then
            input_value="$default_value"
        fi

        if [ "$is_required" = true ] && [ -z "$input_value" ]; then
            echo -e "${RED}✗${NC} $prompt_text is required"
            continue
        fi

        eval "$var_name=\"\$input_value\""
        break
    done
}

echo "========================================"
echo "  Wallet Scripts - Setup"
echo "========================================"
echo

read_config_value "API_TOKEN" "Wallet API Token" "$API_TOKEN" "" true
read_config_value "BASE_URL" "Wallet API Base URL" "$BASE_URL" "$DEFAULT_BASE_URL" true

if [ "$RECONFIGURING" = true ]; then
    echo "Telegram notifications (press Enter to keep current, type 'none' to disable):"
    display_token="not set"
    [ -n "$TELEGRAM_TOKEN" ] && display_token="$TELEGRAM_TOKEN"
    read -r -p "Telegram Bot Token [current: $display_token]: " input_token

    if [ "$input_token" = "none" ] || [ "$input_token" = "NONE" ]; then
        TELEGRAM_TOKEN=""
        CHAT_ID=""
    elif [ -n "$input_token" ]; then
        TELEGRAM_TOKEN="$input_token"
    fi
else
    echo "Optional - Telegram notifications (press Enter to skip):"
    read -r -p "Telegram Bot Token (optional): " TELEGRAM_TOKEN
fi

if [ -n "$TELEGRAM_TOKEN" ]; then
    read_config_value "CHAT_ID" "Telegram Chat ID" "$CHAT_ID" "" true
else
    CHAT_ID=""
fi

cat > "$CONFIG_FILE" <<EOF_CONF
#!/bin/sh

# Wallet Scripts Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

API_TOKEN="$API_TOKEN"
BASE_URL="$BASE_URL"
TELEGRAM_TOKEN="$TELEGRAM_TOKEN"
CHAT_ID="$CHAT_ID"
EOF_CONF

mkdir -p "$SCRIPT_DIR/backups"

chmod +x "$SCRIPT_DIR/bin/"* 2>/dev/null || true
chmod +x "$SCRIPT_DIR/setup.sh" 2>/dev/null || true

echo -e "${GREEN}✓${NC} Configuration saved to config/wallet.conf"
